apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog
spec:
  ports:
  - port: 1313
    name: blog
  clusterIP: None
  selector:
    app: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: blog
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: blog
        command:
        - hugo
        - server
        - -D
        - -e
        - production
        image: lyr8200/blog:v2022.07.01
        imagePullPolicy: Always
        ports:
        - containerPort: 1313
          name: blog